config/routes.rb
Rails.application.routes.draw do


  devise_for :publishers, controllers: { sessions: 'publishers/sessions' }
  devise_for :administrators
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  get 'administrators/dashboard', as: 'administrator_root'
  get 'users/dashboard',          as: 'user_root'
  get 'publishers/dashboard',     as: 'publisher_root'

  root 'site/pages#home'
  get 'sitemap.xml' => 'site/pages#sitemap', format: :xml, as: :sitemap
  get 'robots'      => 'site/pages#robots',  format: :text
  get 'robots.txt'  => 'site/pages#robots',  format: :text
  get 'feeds'       => 'site/pages#feeds', format: 'rss'
  get 'feeds_hot'   => 'site/pages#feeds_hot', format: 'rss'

  # пути для общедоступной части
  scope module: 'site' do
    resources :pages,  only: [:show]
    resources :posts,  only: [:show]
    resources :post_categories,  only: [:show]

    resources :regions, only: [:show]
    resources :cities, only: [:show] do
      get 'test', on: :member
      get 'feed', on: :member, format: 'rss'
    end
    resources :issuers, only: [:show]
    resources :adverts, only: [:show] do
      get 'info', on: :member
    end
    resources :comments, only: [:create, :destroy]
  end

  # пути для админки
  namespace :administrators do
    resources :pages
    resources :posts
    resources :post_categories
    resources :publishers
    resources :cities

    resources :adverts, only: [:new, :create, :edit, :update, :destroy, :index] do
      post 'restore', on: :member
    end
  end

  namespace :publishers do
    resources :posts, only: [:new, :create, :edit, :update, :destroy, :index] do
      post 'publish', on: :member
      post 'unpublish', on: :member
    end
  end

  # редактирование профиля
  match "/publishers/edit_profile" => "publishers/profile#edit_profile", via: [:get]

  # обновление пароля
  match "/publishers/update_password" => "publishers/profile#update_password",
        via: [:post], as: 'update_password_publishers'

  # обновление профиля
  match "/publishers/update_profile" => "publishers/profile#update_profile",
        via: [:post], as: 'update_profile_publishers'


  # получение городов у региона
  match "/api/region_cities" => "site/api#region_cities", via: [:post]

  # получение городов у региона
  match "/api/set_city_id" => "site/api#set_city_id", via: [:post]

  get '/cities/:id/post_categories/:post_category_id',
      to: 'site/cities#post_category',
      as: 'city_post_category'

  get '/search', to: 'site/search#show'
end

app/views/site2/city.html.erb
<% provide(:body_class, 'city') %>

<% provide(:meta_title, @city.meta_title) %>
<% provide(:meta_description, @city.meta_description || "Официальное сетевое издание. На этой странице представлены самые значимые, актуальные и важные новости города #{@city.title_ru}") %>
<% provide(:meta_keywords, @city.meta_keywords) %>

<main class="position-relative">
  <div class="archive-header text-center mb-50">
    <div class="container">
      <h2>
        <span class="colored"><%= @city.base_object.title_ru %></span>
<!--        <span class="post-count">Записей: <%#= @posts.size %> </span>-->
      </h2>
      <div class="breadcrumb">
        <a href="/" rel="nofollow">Главная</a>
        <span></span>
        <a href="#" rel="nofollow"><%= @city.base_object.region.title_ru %></a>
      </div>
    </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-3 primary-sidebar sticky-sidebar sidebar-left order-2 order-md-1">
        <%= render "site2/shared/sidebar/weather", city_weather: @city.city_weather, cached: true %>
        <%= render "site2/shared/sidebar/categories", sidebar_categories: @city.sidebar_categories, cached: true %>
        <%= render "site2/shared/sidebar/adv2", cached: true %>
      </div>
      <!-- main content -->
      <div class="col-lg-10 col-md-9 order-1 order-md-2">
        <div class="row mb-50">
          <div class="col-lg-8 col-md-12">
            <div class="latest-post mb-50">
              <div class="loop-list-style-1 publishers-list">
                <% if @city.publishers.size > 0 %>
                  <% @city.publishers.each do |publisher| %>
                    <% cache publisher do %>
                      <%= render "site2/shared/publisher", publisher: publisher %>
                    <% end %>
                  <% end %>
                <% else  %>
                  <article class="p-10 background-white empty_list border-radius-10 mb-30 wow fadeIn animated">
                     <span class="text-center">
                      <p class="text-center nomargin_bottom">В этом городе пока нет издателей.</p>
                     </span>
                  </article>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-12 sidebar-right">
            <%= render "site2/shared/sidebar/top_posts", posts: @city.top_posts, cached: true %>
            <%= render "site2/shared/sidebar/adv", advert: @city.advert, cached: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/site2/city_post_category.html.erb
<% provide(:body_class, 'category') %>
<% provide(:meta_title, "Новости города #{@city.title_ru} в категории #{@post_category.base_object.title}") %>
<% provide(:meta_description, "Официальное сетевое издание. На этой странице представлены самые значимые, актуальные и важные новости города #{@city.title_ru} в категории #{@post_category.base_object.title}") %>

<main class="position-relative">
  <div class="archive-header text-center mb-50">
    <div class="container">
      <h2>
        <span class="colored"><%= @post_category.base_object.title %></span>
<!--        <span class="post-count">Записей: <%#= @post_category.posts_size %> </span>-->
      </h2>
      <div class="breadcrumb">
        <a href="/" rel="nofollow">Главная</a>
        <span></span>
        <a href="#" rel="nofollow"><%= @city.region.title_ru %></a>
        <span></span>
        <a href="<%= city_path(@city) %>" rel="nofollow"><%= @city.title_ru %></a>
      </div>
    </div>
  </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-3 primary-sidebar sticky-sidebar sidebar-left order-2 order-md-1">
        <%= render "site2/shared/sidebar/weather", city_weather: @city.weather, cached: true %>
        <%= render "site2/shared/sidebar/categories", sidebar_categories: @post_category.sidebar_categories, cached: true %>
      </div>
      <!-- main content -->
      <div class="col-lg-10 col-md-9 order-1 order-md-2">
        <div class="row">
          <div class="col-lg-8 col-md-12">
            <div class="latest-post mb-50">
              <div class="loop-list-style-1 posts_list">
                <% if @posts.size > 0 %>
                  <% @posts.each do |post| %>
                    <% cache post do %>
                      <%= render "site2/shared/article", post: post %>
                    <% end %>
                  <% end %>
                <% else  %>
                  <article class="p-10 background-white empty_list border-radius-10 mb-30 wow fadeIn animated">
                     <span class="text-center">
                      <p class="text-center nomargin_bottom">В этой категории пока нет записей.</p>
                     </span>
                  </article>
                <% end %>
              </div>
            </div>
            <div class="pagination-area mb-30">
              <%= will_paginate @posts %>
            </div>
          </div>
          <div class="col-lg-4 col-md-12 sidebar-right">
            <%= render "site2/shared/sidebar/top_posts", posts: @post_category.top_posts, cached: true %>
            <%= render "site2/shared/sidebar/adv", cached: true, advert: @advert %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/site2/home.html.erb
<% provide(:body_class, 'home') %>
<% provide(:meta_title, @page.base_object.meta_title) %>
<% provide(:meta_description, @page.base_object.meta_description) %>
<% provide(:meta_keywords, @page.base_object.meta_keywords) %>

<main class="position-relative">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-3 primary-sidebar sticky-sidebar sidebar-left order-2 order-md-1">
        <%= render "site2/shared/sidebar/publishers", sidebar_publishers: @page.sidebar_publishers, title: 'Топ издателей', cached: true %>
        <%= render "site2/shared/sidebar/adv2", cached: true %>
        <%= render "site2/shared/sidebar/adv2", cached: true %>
      </div>
      <div class="col-lg-10 col-md-9 order-1 order-md-2">
        <div class="row sidebar_row mb-50">
          <div class="col-lg-8 col-md-12">
            <div class="latest-post">
              <div class="loop-list-style-1">

                <article class="p-10 background-white location_area border-radius-10 wow fadeIn animated">
                  <div class="d-md-flex d-block">
                    <div class="post-content media-body">
                      <% if @page.location %>
                        Последние новости города <span class="city_title colored"><%= link_to @page.location.title_ru, city_path(@page.location) %></span>
                      <% else %>
                        Актуальные новости
                      <% end %>
                    </div>
                  </div>
                </article>

                <div class="publishers-list">
                  <% @page.publishers.each do |publisher| %>
                    <% cache publisher do %>
                      <%= render "site2/shared/publisher", publisher: publisher %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="single-excerpt">
              <p class="font-medium">Вы издательство, блогер или просто хотите попробовать себя в этой сфере ? Напишите на почту admin@vestida.ru для получения доступа к дополнительным возможностям проекта.</p>
            </div>
          </div>
          <div class="col-lg-4 col-md-12 sidebar-right">
            <%= render "site2/shared/sidebar/top_posts", posts: @page.top_posts, cached: true %>
            <%= render "site2/shared/sidebar/adv", advert: @advert, cached: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/site2/page.html.erb
<% provide(:body_class, 'page') %>
<% provide(:meta_title, @page.meta_title) %>
<% provide(:meta_description, @page.meta_description) %>
<% provide(:meta_keywords, @page.meta_keywords) %>

<main class="position-relative">
  <div class="container">
    <% if @page.show_header %>
      <div class="entry-header entry-header-3 mb-50 mt-50 text-center text-white">
        <div class="thumb-overlay img-hover-slide border-radius-5 position-relative" >
          <div class="position-midded">
            <h1 class="post-title mb-30 text-black">
              <%= @page.title %>
            </h1>
          </div>
        </div>
      </div>
    <% end %>
    <!--end entry header-->
    <div class="row mb-50 main-content">
      <div class="col-lg-2 d-none d-lg-block"></div>
      <div class="col-lg-8 col-md-12">
        <div class="single-excerpt">
          <%= @page.description&.html_safe %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/site2/post.html.erb
<% provide(:body_class, 'post') %>
<% provide(:meta_title, @post.base_object.title) %>

<main class="position-relative">
  <div class="container">
    <div class="entry-header entry-header-3 mb-50 mt-50 text-center text-white">
      <div class="thumb-overlay img-hover-slide border-radius-5 position-relative" >
        <div class="position-midded">
          <h1 class="post-title mb-30 text-black">
            <%= @post.base_object.title %>
          </h1>
        </div>
      </div>
    </div>
    <!--end entry header-->
    <div class="row mb-50 main-content">
      <div class="col-lg-2 d-none d-lg-block"></div>
      <div class="col-lg-8 col-md-12">
        <div class="single-excerpt">
          <%= @post.base_object.description&.html_safe %>
        </div>
        <!--author box-->
        <div class="author-bio border-radius-10 bg-white p-30 mb-40 mt-40 ">
          <div class="author-image mb-30">
            <a href="<%= post_path(@post.publisher)%>">
              <% if @post.publisher.avatar.to_s.size > 5 && !Rails.env.development? %>
                <%= image_tag @post.publisher.avatar.s90_90.url %>
              <% else %>
                <%= image_tag 'noimage/main2.png' %>
              <% end %>
            </a>
          </div>
          <div class="author-info">
            <h3><span class="vcard author"><span class="fn"><a href="<%= issuer_path(@post.publisher) %>" title="Posts by Robert" rel="author"><%= @post.publisher.company_name %></a></span></span></h3>
            <div class="author-description"><%= @post.publisher.info %></div>
            <div class="author-social">
            </div>
          </div>
        </div>
        <!--related posts-->
        <div class="related-posts">
          <h3 class="mb-30">Похожие записи</h3>
          <div class="row">
            <% @post.related.each do |post| %>
              <article class="col-lg-4">
              <div class="background-white border-radius-10 p-10 mb-30">
                <div class="post-thumb d-flex mb-15 border-radius-15 img-hover-scale">
                  <a href="<%= post_path(post) %>">
                    <% if post.avatar.to_s.size > 5 && !Rails.env.development?  %>
                      <%= image_tag post.avatar.url %>
                    <% else %>
                      <%= image_tag 'noimage/main2.png' %>
                    <% end %>
                  </a>
                </div>
                <div class="pl-10 pr-10">
                  <div class="entry-meta mb-15 mt-10 category_area">
                    <a class="entry-meta meta-2" href="#">
                      <span class="post-in not-colored font-x-small"><%= post.post_category.title  %></span></a>
                  </div>
                  <h5 class="post-title mb-15">
                  <%= link_to post.title, post_path(post) %>
                  </h5>
                  <div class="entry-meta meta-1 font-x-small color-grey float-left text-uppercase mb-10">
                    <span class="post-by"><%= pretty_datetime(post.created_at) %></span>
                    <span class="hit-count"><i class="ti-eye mr-5"></i><%= post.public_total_views %></span>
                  </div>
                </div>
              </div>
            </article>
            <% end %>
          </div>
        </div>

      </div>
    </div>

    <div class="row mb-50 sidebar-right">
      <%= render "site2/shared/post/hot_posts", posts: @post.hot %>
      <%= render "site2/shared/post/new_posts", posts: @post.new %>
      <%= render "site2/shared/post/viewed_posts", posts: @post.viewed %>
    </div>
  </div>
</main>

app/views/site2/post2.html.erb
<% provide(:body_class, 'post2') %>
<% provide(:meta_title, @post.base_object.title) %>

<% if Sanitize.fragment(@post.base_object.lead).size > 5 %>
  <% provide(:meta_description, Sanitize.fragment(@post.base_object.lead)) %>
<% else %>
  <% provide(:meta_description, Sanitize.fragment(@post.base_object.description.truncate(100))) %>
<% end %>

<main class="position-relative">
  <div class="container">
    <div class="entry-header entry-header-3 mb-50 mt-50 text-center text-white">
      <div class="thumb-overlay img-hover-slide border-radius-5 position-relative" >
        <div class="position-midded">
          <h1 class="post-title text-black mb-30 text-white">
            <%= @post.base_object.title %>
          </h1>
          <div class="entry-meta meta-1 font-x-small color-grey text-uppercase text-white">
            <span class="post-by text-black"><%= link_to @post.post_category.title, city_post_category_path(@post.base_object.city, @post.base_object.post_category) %></span>
            <span class="time-reading text-black"><%= link_to @post.publisher.company_name, issuer_path(@post.base_object.publisher) %></span>
            <span class="post-on text-black"><%= pretty_datetime(@post.base_object.created_at) %></span>

            <p class="font-x-small mt-20 text-black ">
              <span class="hit-count"><i class="ti-eye mr-5"></i><%= @post.base_object.public_total_views %></span>
              <span class="hit-count"><i class="ti-time mr-5"></i><%= time_reading(@post.base_object) %></span>
<!--              <span class="hit-count"><i class="ti-star mr-5"></i>8/10</span>-->
            </p>
          </div>
        </div>
      </div>
    </div>
    <!--end entry header-->
    <div class="row mb-50">
      <div class="col-lg-8 col-md-12">
        <div class="entry-main-content">
          <%= @post.base_object.description&.html_safe %>
        </div>
        <div class="entry-bottom mt-50 mb-30">
<!--          <div class="font-weight-500 entry-meta meta-1 font-x-small color-grey">-->
<!--            <span class="update-on"><i class="ti ti-reload mr-5"></i>Updated 18/09/2020 10:28 EST</span>-->
<!--            <span class="hit-count"><i class="ti-comment"></i>82 comments</span>-->
<!--            <span class="hit-count"><i class="ti-heart"></i>68 likes</span>-->
<!--            <span class="hit-count"><i class="ti-star"></i>8/10</span>-->
<!--          </div>-->
          <div class="overflow-hidden mt-30">
<!--            <div class="tags float-left text-muted mb-md-30">-->
<!--              <span class="font-small mr-10"><i class="fa fa-tag mr-5"></i>Tags: </span>-->
<!--              <a href="category.html" rel="tag">tech</a>-->
<!--              <a href="category.html" rel="tag">world</a>-->
<!--              <a href="category.html" rel="tag">global</a>-->
<!--            </div>-->
            <div class=" float-right">
                <script src="https://yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
                <script src="https://yastatic.net/share2/share.js"></script>
                <div class="ya-share2" data-services="collections,vkontakte,facebook,odnoklassniki,moimir,pocket,viber,whatsapp,skype,telegram"></div>
            </div>
          </div>
        </div>
        <!--author box-->
        <div class="author-bio border-radius-10 bg-white p-30 mb-40 mt-40 ">
          <div class="author-image mb-30">
            <a href="<%= post_path(@post.publisher)%>">
              <% if @post.publisher.avatar.to_s.size > 5 && !Rails.env.development? %>
                <%= image_tag @post.publisher.avatar.s90_90.url %>
              <% else %>
                <%= image_tag 'noimage/main2.png' %>
              <% end %>
            </a>
          </div>
          <div class="author-info">
            <h3><span class="vcard author"><span class="fn"><a href="<%= issuer_path(@post.publisher) %>" title="Posts by Robert" rel="author"><%= @post.publisher.company_name %></a></span></span></h3>
            <div class="author-description"><%= @post.publisher.info %></div>
            <div class="author-social">
            </div>
          </div>
        </div>
        <!--related posts-->
        <%= render "site2/shared/post/related_posts", posts: @post.related, cached: true %>
      </div>
      <!--End col-lg-8-->
      <div class="col-lg-4 col-md-12 sidebar-right sticky-sidebar">
        <div class="pl-lg-50">
          <!--Post aside style 1-->
          <%= render "site2/shared/post/now_read", posts: @post.now_read, cached: true %>
        </div>

        <div class="pl-lg-50">
          <!--Post aside style 1-->
          <%= render "site2/shared/sidebar/adv", advert: @post.advert, cached: true %>
        </div>
      </div>
      <!--End col-lg-4-->
    </div>



    <div class="row mb-50">
      <%= render "site2/shared/post/hot_posts", posts: @post.hot, cached: true %>
      <%= render "site2/shared/post/new_posts", posts: @post.new, cached: true %>
      <%= render "site2/shared/post/viewed_posts", posts: @post.viewed, cached: true %>
    </div>
  </div>
</main>

app/views/site2/publisher.html.erb
<% provide(:body_class, 'publisher') %>
<% provide(:meta_title, @publisher.base_object.company_name) %>
<% provide(:meta_description, "Новости '#{@publisher.base_object.company_name}'") %>


<main class="position-relative">
  <div class="archive-header text-center mb-50">
    <div class="container">
      <h2>
        <span class="colored"><%= @publisher.base_object.company_name %></span>
        <!--        <span class="post-count">Записей: <%#= @posts_size %> </span>-->
      </h2>
      <div class="breadcrumb">
        <a href="/" rel="nofollow">Главная</a>
        <span></span>
        <a href="<%= city_path(@publisher.base_object.city) %>" rel="nofollow">Новости
          города <%= @publisher.city_title %></a>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-3 primary-sidebar sticky-sidebar sidebar-left order-2 order-md-1">
        <%= render "site2/shared/sidebar/weather", city_weather: @publisher.city_weather, cached: true %>
        <%= render "site2/shared/sidebar/categories", sidebar_categories: @publisher.sidebar_categories, cached: true %>
        <%= render "site2/shared/sidebar/adv2", cached: true %>
      </div>
      <!-- main content -->
      <div class="col-lg-10 col-md-9 order-1 order-md-2">
        <div class="row ">
          <div class="col-lg-8 col-md-12">
            <div class="latest-post mb-50">
              <div class="loop-list-style-1 posts_list">
                <% if @posts.size > 0 %>
                  <% @posts.each do |post| %>
                    <% cache post do %>
                      <%= render "site2/shared/article", post: post %>
                    <% end %>
                  <% end %>
                <% else %>
                  <article class="p-10 background-white empty_list border-radius-10 mb-30 wow fadeIn animated">
                     <span class="text-center">
                      <p class="text-center nomargin_bottom">У этого издателя пока нет новостей</p>
                     </span>
                  </article>
                <% end %>
              </div>
            </div>
            <div class="pagination-area mb-30">
              <%= will_paginate @posts %>
            </div>
          </div>
          <div class="col-lg-4 col-md-12 sidebar-right">
            <%= render "site2/shared/sidebar/top_posts", posts: @publisher.top_posts, cached: true %>
            <%= render "site2/shared/sidebar/adv", advert: @publisher.advert, cached: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/site2/search.html.erb
<% provide(:body_class, 'search') %>
<% provide(:meta_title, 'Результаты поиска') %>

<main class="position-relative">
  <div class="archive-header text-center mb-50">
    <div class="container">
      <h2>
        <span class="colored">Результаты поиска</span>
      </h2>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-3 primary-sidebar sticky-sidebar sidebar-left order-2 order-md-1">

      </div>
      <!-- main content -->
      <div class="col-lg-10 col-md-9 order-1 order-md-2">
        <div class="row ">
          <div class="col-lg-8 col-md-12">
            <div class="latest-post mb-50">
              <div class="loop-list-style-1 posts_list">
                <% if @posts.size > 0 %>
                  <% @posts.each do |post| %>
                    <%= render "site2/shared/article", post: post %>
                  <% end %>
                <% else %>
                  <article class="p-10 background-white empty_list border-radius-10 mb-30 wow fadeIn animated">
                     <span class="text-center">
                      <p class="text-center nomargin_bottom">По этому запросу нет записей</p>
                     </span>
                  </article>
                <% end %>
              </div>
            </div>
            <div class="pagination-area mb-30">
              <%= will_paginate @posts %>
            </div>
          </div>
          <div class="col-lg-4 col-md-12 sidebar-right">

          </div>
        </div>
      </div>
    </div>
  </div>
</main>