config/routes.rb
Rails.application.routes.draw do


  devise_for :publishers, controllers: { sessions: 'publishers/sessions' }
  devise_for :administrators
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  get 'administrators/dashboard', as: 'administrator_root'
  get 'users/dashboard',          as: 'user_root'
  get 'publishers/dashboard',     as: 'publisher_root'

  root 'site/pages#home'
  get 'sitemap.xml' => 'site/pages#sitemap', format: :xml, as: :sitemap
  get 'robots'      => 'site/pages#robots',  format: :text
  get 'robots.txt'  => 'site/pages#robots',  format: :text
  get 'feeds'       => 'site/pages#feeds', format: 'rss'
  get 'feeds_hot'   => 'site/pages#feeds_hot', format: 'rss'

  # пути для общедоступной части
  scope module: 'site' do
    resources :pages,  only: [:show]
    resources :posts,  only: [:show]
    resources :post_categories,  only: [:show]

    resources :regions, only: [:show]
    resources :cities, only: [:show] do
      get 'test', on: :member
      get 'feed', on: :member, format: 'rss'
    end
    resources :issuers, only: [:show]
    resources :adverts, only: [:show] do
      get 'info', on: :member
    end
    resources :comments, only: [:create, :destroy]
  end

  # пути для админки
  namespace :administrators do
    resources :pages
    resources :posts
    resources :post_categories
    resources :publishers
    resources :cities

    resources :adverts, only: [:new, :create, :edit, :update, :destroy, :index] do
      post 'restore', on: :member
    end
  end

  namespace :publishers do
    resources :posts, only: [:new, :create, :edit, :update, :destroy, :index] do
      post 'publish', on: :member
      post 'unpublish', on: :member
    end
  end

  # редактирование профиля
  match "/publishers/edit_profile" => "publishers/profile#edit_profile", via: [:get]

  # обновление пароля
  match "/publishers/update_password" => "publishers/profile#update_password",
        via: [:post], as: 'update_password_publishers'

  # обновление профиля
  match "/publishers/update_profile" => "publishers/profile#update_profile",
        via: [:post], as: 'update_profile_publishers'


  # получение городов у региона
  match "/api/region_cities" => "site/api#region_cities", via: [:post]

  # получение городов у региона
  match "/api/set_city_id" => "site/api#set_city_id", via: [:post]

  get '/cities/:id/post_categories/:post_category_id',
      to: 'site/cities#post_category',
      as: 'city_post_category'

  get '/search', to: 'site/search#show'
end

app/views/site2/shared/sidebar/_adv.html.erb
<div class="sidebar-widget adv_widget">
  <div class="post-aside-style-3">
    <article class="bg-white p-10 wow fadeIn animated">
      <div class="post-thumb d-flex img-hover-scale">
        <a href="/pages/about-project">
          <img src="/site2/adv_banner.jpeg" alt="">
        </a>
      </div>
    </article>
  </div>
</div>
<% if defined?(advert) && advert %>
  <div class="sidebar-widget mb-30 second-adv-banner adv_widget adv-banner adv-payed">
    <div class="post-aside-style-3">
      <article class="bg-white border-radius-15 mb-30 p-10 wow fadeIn animated">
        <div class="post-thumb d-flex border-radius-15 img-hover-scale">
          <a href="<%= advert_path(advert.id) %>" target="_blank">
            <% if Rails.env.development? %>
              <img src="/rzd.png" alt="">
            <% else %>
              <%= image_tag advert.image.to_s %>
            <% end %>
          </a>
        </div>
      </article>
    </div>
  </div>
<% end %>

app/views/site2/shared/sidebar/_adv2.html.erb
<div class="sidebar-widget mb-30 second-adv-banner adv-banner">
  <div class="post-aside-style-3">
    <article class="bg-white border-radius-15 mb-30 p-10 wow fadeIn animated">
      <div class="post-thumb d-flex border-radius-15 img-hover-scale">
        <a href="#">
          <img class="border-radius-15" src="/site2/adv.png" alt="">
        </a>
      </div>
    </article>
  </div>
</div>

app/views/site2/shared/sidebar/_categories.html.erb
<div class="sidebar-widget widget_categories border-radius-10 bg-white mb-30">
  <div class="widget-header position-relative mb-15">
    <h5 class="widget-title"><strong>Категории новостей</strong></h5>
  </div>
  <ul class="font-small text-muted">
    <% sidebar_categories.each do |category| %>
      <li class="cat-item cat-item-2 active">
        <a href="<%= city_post_category_url(category[:city_id], category[:category_id]) %>"><%= category[:category_title] %></a></li>
    <% end %>
  </ul>
</div>

app/views/site2/shared/sidebar/_publishers.html.erb
<div class="sidebar-widget widget_categories_2 border-radius-10 bg-white mb-30">
  <div class="widget-header position-relative mb-15">
    <h5 class="widget-title"><strong>
      <% if defined?(title) %>
        <%= title %>
      <% else %>
        Издатели этого города
      <% end %>
        </strong></h5>
  </div>
  <ul class="font-small text-muted">
    <% sidebar_publishers.each do |publisher| %>
      <li class="cat-item cat-item-2 active">
        <a href="<%= issuer_path(publisher[0]) %>"><%= publisher[1] %></a></li>
    <% end %>
  </ul>
</div>

app/views/site2/shared/sidebar/_top_posts.html.erb
<% if posts.size > 0 %>
<div class="sidebar-widget mb-50">
  <div class="widget-header mb-30 bg-white border-radius-10 p-15">
    <h5 class="widget-title mb-0">Горячее</h5>
  </div>
  <div class="post-aside-style-2">
    <ul class="list-post">
      <% posts.each do |post| %>
        <li class="mb-30 wow fadeIn  animated" style="visibility: visible; animation-name: fadeIn;">
        <div class="d-flex">
          <div class="post-thumb d-flex mr-15 border-radius-5 img-hover-scale">
            <a class="color-white" href="<%= post_path(post) %>">
              <% if post.avatar.to_s.size > 5 && !Rails.env.development? %>
                <img src="<%= post.avatar.s87_87.url %>" width="87">
              <% else %>
                <%= image_tag "noimage/main2.png", width: 87 %>
              <% end %>
            </a>
          </div>
          <div class="post-content media-body">
            <h6 class="post-title mb-10 text-limit-2-row">
              <%= link_to post.title, post_path(post) %>
            </h6>
            <div class="entry-meta meta-1 font-x-small color-grey float-left text-uppercase">
              <span class="post-by"><%= link_to post.post_category&.title, city_post_category_path(post.city_id, post.post_category_id) %></span>
              <span class="post-on"><%= pretty_datetime(post.created_at) %></span>
            </div>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/site2/shared/sidebar/_weather.html.erb
<div class="sidebar-widget widget-weather border-radius-10 bg-white mb-30">
  <div class="d-flex">
    <% if city_weather %>
      <%= city_weather.html_safe %>
    <% else %>
      <a href="https://clck.yandex.ru/redir/dtype=stred/pid=7/cid=1228/*https://yandex.ua/pogoda/10864" target="_blank"><img src="https://info.weather.yandex.net/10864/1_white.ru.png?domain=ua" border="0" alt="Яндекс.Погода"/><img width="1" height="1" src="https://clck.yandex.ru/click/dtype=stred/pid=7/cid=1227/*https://img.yandex.ru/i/pix.gif" alt="" border="0"/></a>
    <% end %>
  </div>
</div>