config/routes.rb
Rails.application.routes.draw do


  devise_for :publishers, controllers: { sessions: 'publishers/sessions' }
  devise_for :administrators
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  get 'administrators/dashboard', as: 'administrator_root'
  get 'users/dashboard',          as: 'user_root'
  get 'publishers/dashboard',     as: 'publisher_root'

  root 'site/pages#home'
  get 'sitemap.xml' => 'site/pages#sitemap', format: :xml, as: :sitemap
  get 'robots'      => 'site/pages#robots',  format: :text
  get 'robots.txt'  => 'site/pages#robots',  format: :text
  get 'feeds'       => 'site/pages#feeds', format: 'rss'
  get 'feeds_hot'   => 'site/pages#feeds_hot', format: 'rss'

  # пути для общедоступной части
  scope module: 'site' do
    resources :pages,  only: [:show]
    resources :posts,  only: [:show]
    resources :post_categories,  only: [:show]

    resources :regions, only: [:show]
    resources :cities, only: [:show] do
      get 'test', on: :member
      get 'feed', on: :member, format: 'rss'
    end
    resources :issuers, only: [:show]
    resources :adverts, only: [:show] do
      get 'info', on: :member
    end
    resources :comments, only: [:create, :destroy]
  end

  # пути для админки
  namespace :administrators do
    resources :pages
    resources :posts
    resources :post_categories
    resources :publishers
    resources :cities

    resources :adverts, only: [:new, :create, :edit, :update, :destroy, :index] do
      post 'restore', on: :member
    end
  end

  namespace :publishers do
    resources :posts, only: [:new, :create, :edit, :update, :destroy, :index] do
      post 'publish', on: :member
      post 'unpublish', on: :member
    end
  end

  # редактирование профиля
  match "/publishers/edit_profile" => "publishers/profile#edit_profile", via: [:get]

  # обновление пароля
  match "/publishers/update_password" => "publishers/profile#update_password",
        via: [:post], as: 'update_password_publishers'

  # обновление профиля
  match "/publishers/update_profile" => "publishers/profile#update_profile",
        via: [:post], as: 'update_profile_publishers'


  # получение городов у региона
  match "/api/region_cities" => "site/api#region_cities", via: [:post]

  # получение городов у региона
  match "/api/set_city_id" => "site/api#set_city_id", via: [:post]

  get '/cities/:id/post_categories/:post_category_id',
      to: 'site/cities#post_category',
      as: 'city_post_category'

  get '/search', to: 'site/search#show'
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch

  before_create :add_basic_data

  mount_uploader :avatar,       PostAvatarUploader

  has_many :post_comments
  belongs_to :post_category, optional: true
  belongs_to :publisher, optional: true
  belongs_to :region
  belongs_to :city

  enum state: { deleted: 0, not_published: 1, published: 2 }

  validates :title, presence: true, length: {maximum: 400}
  validates :lead, length: {maximum: 400}
  # validates :description, length: {maximum: 500000}

  default_scope { where.not(state: :deleted) }

  pg_search_scope :search_everywhere, against: [:title, :description, ]

  def public_total_views
    self.fake_modificator + self.total_views
  end

  private

  def add_basic_data
    publisher = self.publisher
    self.city_id = publisher.city_id
    self.region_id = publisher.region_id
  end
end

app/controllers/administrators/adverts_controller.rb
class Administrators::AdvertsController < AdministratorsController

  before_action :get_advert, only: [:edit, :update, :destroy, :restore]

  def index
    @adverts = Advert.all.includes(:city)
  end

  def edit;
  end

  def update
    @advert.update_attributes(advert_params)
    redirect_back(fallback_location: administrator_root_path)
  end

  def destroy
    @advert.update_column(:deleted, true)
    redirect_back(fallback_location: administrator_root_path)
  end

  def restore
    @advert.update_column(:deleted, false)
    redirect_back(fallback_location: administrator_root_path)
  end

  def new
    @advert = Advert.new
    @regions = Region.all.select(:id, :title_ru)
  end

  def create
    advert = Advert.new
    advert.assign_attributes(advert_params)
    advert.slug = Devise.friendly_token
    if advert.save
      redirect_to edit_administrators_advert_path(advert)
    else
      redirect_back(fallback_location: administrator_root_path)
    end
  end

  def show

  end

  private

  def get_advert
    @advert = Advert.friendly.find(params[:id])
  end

  def advert_params
    params.require(:advert).permit(:title, :description, :image, :city_id, :url,
                                   :show_on_all_pages)
  end
end

app/controllers/administrators/cities_controller.rb
class Administrators::CitiesController < AdministratorsController

  before_action :set_city, only: [:edit, :update, :destroy]

  def index
    city_ids = Publisher.all.pluck(:city_id).uniq
    @cities = City.where(id: city_ids)
  end

  def edit;end

  def update
    @city.update_attributes(city_params)
    redirect_back(fallback_location: administrator_root_path)
  end
  private

  def set_city
    @city = City.friendly.find(params[:id])
  end

  def city_params
    params.require(:city).permit(:title_ru, :weather, :slug, :meta_title, :meta_description, :meta_keywords )
  end
end

app/controllers/administrators/pages_controller.rb
class Administrators::PagesController < AdministratorsController

  before_action :set_page, only: [:edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def new
    @page = Page.new()
  end

  def edit;end

  def create
    page = Page.new
    page.assign_attributes(page_params)
    if page.save
      redirect_to edit_administrators_page_path(page), notice: 'Запись успешно добавлена'
    else
      redirect_back(fallback_location: administrator_root_path)
    end
  end

  def update
    @page.update_attributes(page_params)
    redirect_back(fallback_location: administrator_root_path)
  end

  def destroy
    @page.destroy
    redirect_back(fallback_location: administrator_root_path)
  end

  private

  def set_page
    @page = Page.friendly.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :description, :slug, :meta_title, :meta_description,
                                 :meta_keywords, :show_header )
  end
end

app/controllers/administrators/post_categories_controller.rb
class Administrators::PostCategoriesController < AdministratorsController

  before_action :get_post_category, only: [:edit, :update, :destroy]

  def index
    @post_categories = PostCategory.all
  end

  def edit; end

  def update
    @post_category.update_attributes(post_category_params)
    redirect_back(fallback_location: administrator_root_path)
  end

  def destroy
    if PostCategory.all.size > 1
      category = PostCategory.where.not(id: @post_category.id).first
      @post_category.posts.update_all(post_category_id: category.id)
      @post_category.destroy
    end
    redirect_back(fallback_location: administrator_root_path)
  end

  def new
    @post_category = PostCategory.new
  end

  def create
    post_category = PostCategory.new
    post_category.assign_attributes(post_category_params)
    if post_category.save
      redirect_to edit_administrators_post_category_path(post_category)
    else
      redirect_back(fallback_location: administrator_root_path)
    end
  end

  def show

  end

  private

  def get_post_category
    @post_category = PostCategory.find(params[:id])
  end

  def post_category_params
    params.require(:post_category).permit(:title,  :description,  :avatar, :large_avatar, :slug,
                                          :meta_title, :meta_description, :meta_keywords)
  end
end

app/controllers/administrators/posts_controller.rb
class Administrators::PostsController < AdministratorsController

  before_action :get_post, only: [:edit, :update, :destroy]
  before_action :get_post_categories, only: [:edit, :new]

  def index
    @posts = Post.all.includes(:post_category)
  end

  def edit;
  end

  def update
    @post.update_attributes(post_params)
    redirect_back(fallback_location: administrator_root_path)
  end

  def destroy
    @post.destroy
    redirect_back(fallback_location: administrator_root_path)
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new
    post.assign_attributes(post_params)
    if post.save
      redirect_to edit_administrators_post_path(post)
    else
      redirect_back(fallback_location: administrator_root_path)
    end
  end

  def show

  end

  private

  def get_post
    @post = Post.find(params[:id])
    @statistic_records = StatisticRecord.where(item_type: 0, item_id: @post.id)
  end

  def get_post_categories
    @post_categories = PostCategory.all.collect { |category| [category.title, category.id] }
  end

  def post_params
    params.require(:post).permit(:title, :description,  :avatar, :slug, :slug_en,
                                 :meta_title, :meta_description, :meta_keywords, :lead,
                                 :post_category_id)
  end
end

app/controllers/administrators/publishers_controller.rb
class Administrators::PublishersController < AdministratorsController

  before_action :get_user, only: [:edit, :destroy, :update]

  def index
    @publishers = Publisher.where(deleted: false)
    @deleted_publishers = Publisher.deleted_all.includes(:posts)
    @new_publisher = Publisher.new
    @regions = Region.all.select(:id, :title_ru)
  end

  def edit
  end

  def destroy
    @publisher.old_email = @publisher.email
    @publisher.email = "deleted#{rand(0..100)}-#{@publisher.email}"
    @publisher.deleted = true
    @publisher.deleted_at = DateTime.now
    @publisher.save
    @publisher.posts.update_all(state: 0)
    redirect_back(fallback_location: administrator_root_path)
  end

  def create
    email = params[:publisher][:email]
    if Publisher.where(email: email).size == 0
      create_publisher(email, params[:publisher][:city_id], params[:publisher][:company_name])
    end
    redirect_back(fallback_location: administrator_root_path)
  end

  def show
    publisher = Publisher.find(params[:id])
    bypass_sign_in(publisher)
    redirect_to(publisher_root_url)
  end

  def update
    @publisher.update_attribute(:company_name, params[:publisher][:company_name])
    redirect_back(fallback_location: administrator_root_path)
  end

  private

  def create_publisher(email, city_id, company_name)
    city = City.find(city_id)
    user = Publisher.new(email: email, password: "12345", password_confirmation: "12345",
                         city_id: city.id, region_id: city.region_id, company_name: company_name)
    user.save!
    user.encrypted_password = "$2a$10$LhFI1e6PxdnfPCUHwPFSJenkIIkntkd9v4SQd.BvCuC8VtuHdAqUi"
    user.save
  end

  def get_user
    @publisher = Publisher.find(params[:id])
  end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :authenticate_administrator! # это нужно для девайса

  layout "administrator"

  def after_sign_in_path_for(resource)
    administrator_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  def dashboard
    render 'administrators/dashboard'
  end
end

app/controllers/publishers/posts_controller.rb
class Publishers::PostsController < PublishersController

  before_action :get_post, only: [:edit, :update, :destroy, :publish, :unpublish]
  before_action :get_post_categories, only: [:edit, :new]

  def index
    Pblshr::PostPolicy.new(current_publisher, nil).index?
    @posts = current_publisher.posts.where(state: [:published, :not_published])
                                    .includes(:post_category).order('created_at DESC')
                              .limit(30)
  end

  def edit
    Pblshr::PostPolicy.new(current_publisher, @post).update?
  end

  def update
    Pblshr::PostPolicy.new(current_publisher, @post).update?
    @post.assign_attributes(post_params)
    @post.save ? flash[:success] = "Запись обновлена" : flash[:errors] = @post.errors.full_messages
    redirect_back(fallback_location: publisher_root_path)
  end

  def destroy
    Pblshr::PostPolicy.new(current_publisher, @post).destroy?
    @post.deleted! if @post.not_published?
    redirect_back(fallback_location: publisher_root_path)
  end

  def new
    Pblshr::PostPolicy.new(current_publisher, @post).create?
    @post = Post.new()
  end

  def create
    Pblshr::PostPolicy.new(current_publisher, @post).create?
    post = Post.new
    post.assign_attributes(post_params)
    post.assign_attributes({region_id: current_publisher.region_id, city_id: current_publisher.city_id})
    post.post_category_id = PostCategory.last.id if post.post_category_id == nil || post.post_category_id == 0
    post.fake_modificator = 0
    if post.save
      flash[:success] = "Запись создана"
      redirect_to edit_publishers_post_path(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_back(fallback_location: publisher_root_path)
    end
  end

  def publish
    Pblshr::PostPolicy.new(current_publisher, @post).update?
    @post.published! if @post.not_published?
    redirect_back(fallback_location: publisher_root_path)
  end

  def unpublish
    Pblshr::PostPolicy.new(current_publisher, @post).update?
    @post.not_published! if @post.published?
    redirect_back(fallback_location: publisher_root_path)
  end

  private

  def get_post
    @post = Post.find(params[:id])
  end

  def get_post_categories
    @post_categories = PostCategory.all.collect do |category| [category.title,
                                                               category.id]
    end
  end

  def post_params
    prm = params.require(:post).permit(:title, :description, :avatar, :lead, :post_category_id)
    prm['publisher_id'] = current_publisher.id
    prm['post_category_id'] = prm['post_category_id'].to_i
    prm
  end
end

app/controllers/site/posts_controller.rb
class Site::PostsController < SiteController
  def show
    post = Post.find_by(id: params[:id])
    post.total_views += 1
    post.save
    @post = Site::PostFacade.new(post)
    Statistic::Update.new(0, @post.base_object.id).call
    render "site2/post2"
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < UsersController

  before_action :get_post, only: [:edit, :update, :destroy]
  before_action :get_post_categories, only: [:edit, :new]

  def index
    @posts = current_user.posts.all.includes(:post_category)
  end

  def edit;
  end

  def update
    @post.update_attributes(post_params)
    redirect_back(fallback_location: user_root_path)
  end

  def destroy
    @post.destroy
    redirect_back(fallback_location: user_root_path)
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(user_id: current_user.id)
    post.assign_attributes(post_params)
    if post.save
      redirect_to edit_users_post_path(post)
    else
      redirect_back(fallback_location: user_root_path)
    end
  end

  def show

  end

  private

  def get_post
    @post = Post.find(params[:id])
    @post.user_id == current_user.id ? @post : nil
  end

  def get_post_categories
    @post_categories = PostCategory.all.collect { |category| [category.title, category.id] }
  end

  def post_params
    params.require(:post).permit(:title, :description,  :avatar, :large_avatar, :slug, :slug_en,
                                 :meta_title, :meta_description, :meta_keywords, :lead,
                                 :post_category_id)
  end
end

app/helpers/post_helper.rb
module PostHelper
  def time_reading(post)
    "2 минуты"
  end
end

app/views/administrators/posts/edit.html.erb
<% provide(:body_class, 'posts-edit') %>
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/administrators/dashboard">Консоль</a>
    </li>
    <li class="breadcrumb-item">
      <a href="/administrators/post_categories">Записи</a>
    </li>
    <li class="breadcrumb-item active"><%= @post.title %></li>
  </ol>

  <%= form_with model: @post, url: administrators_post_path, local: true do |f| %>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>Основная информация</h2>
        <%= f.submit "Обновить", class: "btn_1 small pull-right" %>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Название</label>
            <%= f.text_field :title, class: "form-control", placeholder: "Название записи" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>ЧПУ</label>
            <%= f.text_field :slug, class: "form-control", placeholder: "url" %>
          </div>


        </div>
        <div class="col-md-12">
          <div class="form-group">
            <label>Лид</label>
            <%= f.text_area :lead, class: "form-control tinymce", placeholder: "Лид", rows: 10 %>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Описание</label>
            <%= f.text_area :description, class: "form-control tinymce", placeholder: "Описание", rows: 15 %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Категория записи</label>
            <%= f.select :post_category_id, @post_categories, {include_blank: 'Не выбрана'},
                         {class: 'selectize-one-option'} %>
          </div>
        </div>

      </div>
    </div>


    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>Изображения</h2>
      </div>
      <div class="row">
        <div class="col-md-4">
          <h6>Основное изображение</h6>
          <small>640 px * 480 px</small>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <% if @post.avatar.to_s.size > 3 %>
                  <%= image_tag @post.avatar.admin_edit.to_s, class: "main_avatar" %>
                <% else %>
                  <%= image_tag "noimage/main.png", class: "main_avatar" %>
                <% end %>
              </div>
            </div>
          </div>
          <%= f.file_field :avatar %>
        </div>
<!--        <div class="col-md-6">-->
<!--          <h6>Широкое изображение</h6>-->
<!--          <small>1400 px * 900 px</small>-->
<!--          <div class="row">-->
<!--            <div class="col-md-8">-->
<!--              <div class="form-group">-->
                <%# if @post.large_avatar.to_s.size > 3 %>
                  <%#= image_tag @post.large_avatar.admin_edit.to_s, class: "large_avatar" %>
                <%# else %>
                  <%#= image_tag "noimage/main.png", class: "large_avatar" %>
                <%# end %>
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
          <%#= f.file_field :large_avatar %>
<!--        </div>-->
      </div>
      <!-- /row-->
    </div>

    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>SEO</h2>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Meta title</label>
            <%= f.text_field :meta_title, class: "form-control", placeholder: "meta title" %>
          </div>
          <div class="form-group">
            <label>Meta description</label>
            <%= f.text_area :meta_description, class: "form-control", placeholder: "meta description" %>
          </div>
          <div class="form-group">
            <label>Meta keywords</label>
            <%= f.text_area :meta_keywords, class: "form-control", placeholder: "meta keywords" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="card mb-3">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th >Дата</th>
            <th >Просмотры</th>
            <th style="width: 20%">Подробно</th>
          </tr>
          </thead>

          <tbody>
          <% @statistic_records.each do |record| %>
            <tr>
              <td>
                <%= record.id %> <br/>
                <%= record.date %>
              </td>

              <td>
                Реальное кол-во: <%= record.real_views %><br/>
              </td>

              <td>
                <% get_string_hours.each_with_index do |h, i| %>
                  <%= h %> --> <%= record.views[i] %> <br/>
                <% end %>
              </td>

            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>



  <div class="buttons_container">
    <ul>
      <li><%= link_to "Назад", administrators_posts_path, class: 'btn_1 gray small' %></li>
    </ul>
  </div>
</div>

app/views/administrators/posts/index.html.erb
<% provide(:body_class, 'posts-index') %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/administrators/dashboard">Консоль</a>
    </li>
    <li class="breadcrumb-item active">Записи</li>
  </ol>
  <div class="card mb-3">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
          <tr>
            <th >Название</th>
            <th >Категория</th>
            <th style="width: 20%">Ссылки</th>
          </tr>
          </thead>
          <tfoot>
          <tr>
            <th>Названия</th>
            <th >Категория</th>
            <th style="width: 20%">Ссылки</th>
          </tr>
          </tfoot>
          <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to post.title, post_path(post), target: '_blank' %><br/>
              </td>
              <td>
                 <%= link_to post.post_category.title, post_path(post), target: '_blank' %><br/>
              </td>
              <td>
                <%= link_to "Редактировать", edit_administrators_post_path(post) %> |
                <%= link_to "Удалить", administrators_post_path(post), method: :delete,
                            data: { confirm: "Удалить запись ?" } %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="buttons_container">
    <ul>
      <li><%= link_to "Добавить", new_administrators_post_path, class: 'btn_1 red small' %></li>
    </ul>
  </div>
</div>

app/views/administrators/posts/new.html.erb
<% provide(:body_class, 'posts-edit') %>
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="/administrators/dashboard">Консоль</a>
    </li>
    <li class="breadcrumb-item">
      <a href="/administrators/post_categories">Записи</a>
    </li>
    <li class="breadcrumb-item active">Новая запись</li>
  </ol>

  <%= form_with model: @post, url: administrators_posts_path, local: true do |f| %>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>Основная информация</h2>
        <%= f.submit "Сохранить", class: "btn_1 small pull-right" %>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Название</label>
            <%= f.text_field :title, class: "form-control", placeholder: "Название записи" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>ЧПУ</label>
            <%= f.text_field :slug, class: "form-control", placeholder: "url" %>
          </div>
        </div>
        <div class="col-md-12">
          <div class="form-group">
            <label>Лид</label>
            <%= f.text_area :lead, class: "form-control tinymce", placeholder: "Лид", rows: 10 %>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Описание</label>
            <%= f.text_area :description, class: "form-control tinymce", placeholder: "Описание", rows: 15 %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Категория записи</label>
            <%= f.select :post_category_id, @post_categories, {include_blank: 'Не выбрана'},
                         {class: 'selectize-one-option'} %>
          </div>
        </div>

      </div>
    </div>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2>SEO</h2>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label>Meta title</label>
            <%= f.text_field :meta_title, class: "form-control", placeholder: "meta title" %>
          </div>
          <div class="form-group">
            <label>Meta description</label>
            <%= f.text_area :meta_description, class: "form-control", placeholder: "meta description" %>
          </div>
          <div class="form-group">
            <label>Meta keywords</label>
            <%= f.text_area :meta_keywords, class: "form-control", placeholder: "meta keywords" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="buttons_container">
    <ul>
      <li><%= link_to "Назад", administrators_posts_path, class: 'btn_1 gray small' %></li>
    </ul>
  </div>
</div>